<template>
  <el-dropdown @command="handleCommand">
    <button class="lang-trigger" :class="{ 'icon-only': collapsed }">
      <el-icon><Switch /></el-icon>
      <span v-if="!collapsed" class="lang-text">{{ currentLangText }}</span>
    </button>
    <template #dropdown>
      <el-dropdown-menu>
        <el-dropdown-item command="zh-CN" :disabled="currentLang === 'zh-CN'">
          🇨🇳 简体中文
        </el-dropdown-item>
        <el-dropdown-item command="en-US" :disabled="currentLang === 'en-US'">
          🇺🇸 English
        </el-dropdown-item>
      </el-dropdown-menu>
    </template>
  </el-dropdown>
</template>

<script setup lang="ts">
import { ref, computed } from 'vue'

defineProps<{ collapsed?: boolean }>()
import { useI18n } from 'vue-i18n'
import { setLanguage } from '@/locales'
import { ElMessage, ElMessageBox } from 'element-plus'
import { settingsAPI } from '@/api/settings'

const { locale } = useI18n()

const currentLang = ref(locale.value)
const loading = ref(false)

const currentLangText = computed(() => {
  return currentLang.value === 'zh-CN' ? '中文' : 'English'
})

const handleCommand = async (lang: string) => {
  if (loading.value) return
  
  // 将 zh-CN/en-US 转换为 zh/en (后端格式)
  const backendLang = lang === 'zh-CN' ? 'zh' : 'en'
  const currentBackendLang = currentLang.value === 'zh-CN' ? 'zh' : 'en'
  
  // 双语确认消息
  const confirmMessage = backendLang === 'zh' 
    ? `切换为中文后，后端生成的所有提示词、角色描述、场景描述等都将使用中文。是否继续？


After switching to Chinese, all prompts, character descriptions, scene descriptions generated by the backend will use Chinese. Continue?`
    : `After switching to English, all prompts, character descriptions, scene descriptions generated by the backend will use English. Continue?


切换为英文后，后端生成的所有提示词、角色描述、场景描述等都将使用英文。是否继续？`
  
  try {
    await ElMessageBox.confirm(
      confirmMessage,
      '切换语言 / Switch Language',
      {
        confirmButtonText: '确定 / Confirm',
        cancelButtonText: '取消 / Cancel',
        type: 'warning',
        dangerouslyUseHTMLString: false
      }
    )

    loading.value = true
    
    // 调用后端API更新语言设置
    const res = await settingsAPI.updateLanguage(backendLang)

    // 更新前端语言
    setLanguage(lang)
    currentLang.value = lang
    
    // 使用后端返回的双语消息（request拦截器已经返回了data）
    ElMessage.success({
      message: res?.message || (backendLang === 'zh' ? '语言已切换为中文' : 'Language switched to English'),
      duration: 3000
    })
  } catch (error: any) {
    if (error !== 'cancel') {
      console.error('Failed to switch language:', error)
      
      // 安全获取错误消息
      let errorMessage = '未知错误'
      if (error?.message) {
        errorMessage = error.message
      } else if (error?.response?.data?.error?.message) {
        errorMessage = error.response.data.error.message
      } else if (typeof error === 'string') {
        errorMessage = error
      }
      
      // 双语错误提示
      const errorMsg = currentBackendLang === 'zh'
        ? `切换语言失败: ${errorMessage}`
        : `Failed to switch language: ${errorMessage}`
      
      ElMessage.error({
        message: errorMsg,
        duration: 5000
      })
    }
  } finally {
    loading.value = false
  }
}
</script>

<style scoped>
.lang-trigger {
  display: flex;
  align-items: center;
  justify-content: center;
  gap: 6px;
  height: 36px;
  padding: 0 10px;
  border: 1px solid var(--border-primary);
  border-radius: var(--radius-md);
  background: var(--bg-card);
  color: var(--text-secondary);
  cursor: pointer;
  transition: all 150ms;
  white-space: nowrap;
  font-size: 13px;
}

.lang-trigger.icon-only {
  width: 36px;
  padding: 0;
}

.lang-trigger:hover {
  background: var(--bg-card-hover);
  color: var(--text-primary);
  border-color: var(--border-secondary);
}

.lang-trigger:focus-visible {
  outline: 2px solid var(--accent);
  outline-offset: 2px;
}

.lang-text {
  color: inherit;
}
</style>
